# Generated by Django 2.1.7 on 2019-04-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20190416_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='img_url',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
