# Generated by Django 2.1.7 on 2019-06-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_phone_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminkey', models.CharField(max_length=20)),
                ('adminpwd', models.CharField(max_length=20)),
            ],
        ),
    ]
